[package]
name = "scriptplan-cli"
version = "1.0.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4.5"
clap = "2.33.3"
conch-parser = { version = "0.1" }
conch-runtime = { git = "https://github.com/ipetkov/conch-runtime" }
tokio = { version = "0.2", features = ["fs", "io-util", "process", "macros"] }
shellwords = { version = "1.1.0" }
async-trait = { version = "0.1.50" }
async-recursion = { version = "0.3.2" }
futures = { version = "0.3.15" }
