[package]
name = "spot-welder-arduino"
version = "0.1.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2018"
publish = false

[dependencies]
panic-halt = "0.2.0"
nb = "0.1.2"
ufmt = "0.1.0"
avr-device = "0.3.1"

[dependencies.arduino-uno]
git = "https://github.com/rahix/avr-hal"
rev = "a20277873a8102998d5fd69743771bd8c0aa9423"

[build]
# Default target
target = "avr-unknown-unknown"
